import { rollDie } from "./dice.ts";
import type { RNG } from "./rng.ts";
import {
  CITY_OR_FORTRESS,
  COLD_TERRAIN_TABLE,
  HOT_TERRAIN_TABLE,
  LOCATION_TABLE,
  type Climate,
  type ColdTerrain,
  type HotTerrain,
  type Land,
  type LocationKind,
  type Terrain,
} from "../data/hexTables.ts";
import { CULTURE_BY_LOCATION, type CityCulture } from "../data/affinity.ts";
import { CITY_NAME_PREFIX, CITY_NAME_SUFFIX } from "../data/cityNames.ts";
import type { AnimalDef } from "../data/types.ts";

export interface HexCoord {
  q: number;
  r: number;
}

export function hexKey(c: HexCoord): string {
  return `${c.q},${c.r}`;
}

/** Axial neighbor offsets, pointy-top hexes. */
export const HEX_DIRECTIONS: readonly HexCoord[] = [
  { q: 1, r: 0 },
  { q: 1, r: -1 },
  { q: 0, r: -1 },
  { q: -1, r: 0 },
  { q: -1, r: 1 },
  { q: 0, r: 1 },
];

export function hexNeighbors(c: HexCoord): HexCoord[] {
  return HEX_DIRECTIONS.map((d) => ({ q: c.q + d.q, r: c.r + d.r }));
}

export interface HexTile {
  terrain: Terrain;
  location: LocationKind | null;
  /** The PendingDungeon.id found here, once "Enter Dungeon" has been used on this hex -- lets a
   * later visit (same character returning, or a new one taking over) resume the same dungeon
   * instead of rolling fresh. Set once, on first entry; never cleared, even once beaten. */
  dungeonRunId?: string;
  /** Set by the "Ask" City Action (`findAskedDungeonHex`/`withDungeonMarked`) the moment a nearby
   * dungeon hex is found -- "draw the dungeon on the map" happens here, before the player has ever
   * set foot on this tile or a `dungeonRunId`/`PendingDungeon` exists for it. Once the player
   * actually travels here and uses "Enter Dungeon", the normal first-entry flow takes over exactly
   * as it does for a City/Fortress/Ruins hex -- this flag only ever widens *which* hexes can offer
   * that button, it never itself mints a run. */
  dungeonMarked?: boolean;
  /** A generated proper name (issue #49), set once -- alongside `terrain`/`location` -- the moment
   * a City/Fortress location is first rolled, so it's stable for that hex forever. Only ever set
   * for a City/Fortress `location` (see `rollCityName()`); everything else (Ruins, water, "It was
   * nothing...," etc.) has no identity of its own to name. Optional so a session persisted before
   * this field existed still loads -- an old city with no name falls back to its generic
   * `LOCATION_LABEL` wherever this is displayed. */
  name?: string;
}

export interface WorldState {
  /** Always "hot" for now -- the cold table is real data but nothing picks it yet. */
  climate: Climate;
  home: HexCoord;
  player: HexCoord;
  /** Sparse, populated lazily -- a tile only exists once its terrain+location are rolled,
   * mirroring DungeonState's segments (which likewise don't exist until a door reveals them). The
   * rulebook rolls a hex's location the same moment it rolls its terrain (both happen when its
   * *parent* hex is entered), so there's no separate "terrain known, location TBD" state to model
   * -- presence in this map means fully known. */
  tiles: Record<string, HexTile>;
  /** "Hire Boat" (a City Action, see `town.ts`/`TownScreen.tsx`) -- true for exactly one `MOVE`
   * onto water; "once you enter non-water terrain you leave the boat" clears it automatically the
   * moment the player lands somewhere that isn't water again. */
  hasBoat: boolean;
  /** Thug Life's failed-escape outcome ("you have fled, and will no longer be able to enter this
   * city") -- hex keys the player is permanently barred from entering, world-scoped like
   * `dungeonRunId`/discovered tiles rather than tied to any one character (this app has no
   * per-character bucket on `WorldState` to scope a ban to any more narrowly -- see CLAUDE.md's
   * "Getting Money" note). Optional so a session persisted before this field existed still loads;
   * always read via `isBannedHex()`, never directly, so that default stays in one place. */
  bannedHexes?: string[];
}

/** `current` is trusted to belong to `climate`'s own terrain set (a hot-climate world only ever
 * produces HotTerrain values, a cold one only ColdTerrain) -- true by construction, since every
 * tile in a WorldState is generated by this same function against the same fixed climate. */
function nextTerrain(current: Terrain, climate: Climate, roll: number): Terrain {
  if (climate === "hot") return HOT_TERRAIN_TABLE[roll]![current as HotTerrain];
  return COLD_TERRAIN_TABLE[roll]![current as ColdTerrain];
}

/** City/Fortress name generator (issue #49) -- two 1d6 rolls (prefix, suffix) against the given
 * culture's `CITY_NAME_PREFIX`/`CITY_NAME_SUFFIX` tables (`data/cityNames.ts`), joined into one
 * compound word (e.g. "Iron" + "hold" -> "Ironhold"). Not from the rulebook, mirroring
 * `dungeonTypes.ts`'s own "second part"/"third part" flavor-name combination. */
export function rollCityName(culture: CityCulture, rng: RNG): string {
  const prefix = CITY_NAME_PREFIX[culture][rollDie(rng)]!;
  const suffix = CITY_NAME_SUFFIX[culture][rollDie(rng)]!;
  return `${prefix}${suffix}`;
}

/**
 * "When entering a hex, first determine the neighboring hexes. Roll one die in the Terrain table
 * for each hex. After that, roll one more die for each hex to see if there is a location. If it
 * lands on 6, there is a location -- roll on the Location table." Mutates `tiles` in place (works
 * whether it's a plain object, as in `createInitialWorldState`, or an Immer `Draft`, as in
 * `hexReducer`'s `produce()`) and never overwrites an already-revealed tile, so a hex shared by
 * two revealed neighbors only ever gets rolled once. A City/Fortress location also gets a
 * `rollCityName()` name in the same pass, right where its `location` itself is decided.
 */
export function revealNeighborsInPlace(
  tiles: Record<string, HexTile>,
  of: HexCoord,
  climate: Climate,
  rng: RNG,
): void {
  const parent = tiles[hexKey(of)];
  if (!parent) return;
  for (const neighbor of hexNeighbors(of)) {
    const key = hexKey(neighbor);
    if (tiles[key]) continue;
    const terrain = nextTerrain(parent.terrain, climate, rollDie(rng));
    const hasLocation = rollDie(rng) === 6;
    const location = hasLocation ? LOCATION_TABLE[rollDie(rng)]![terrain as Land] : null;
    const culture = location ? CULTURE_BY_LOCATION[location] : undefined;
    tiles[key] = culture ? { terrain, location, name: rollCityName(culture, rng) } : { terrain, location };
  }
}

/** Animals (issue #26): how many of `coord`'s six neighbors already share `terrain` -- both
 * acquisition paths ("train in the wild," "buy a mount in a qualifying city") require at least 2. */
export function countMatchingNeighbors(
  tiles: Record<string, HexTile>,
  coord: HexCoord,
  terrain: Terrain,
): number {
  return hexNeighbors(coord).filter((n) => tiles[hexKey(n)]?.terrain === terrain).length;
}

/** "This land must be empty (no location) and have at least 2 lands of the same type adjacent to
 * it." An empty `animal.terrain` (Snake's "Any") always matches terrain-wise. */
export function qualifiesForTraining(tile: HexTile, matchingNeighbors: number, animal: AnimalDef): boolean {
  const terrainMatches = animal.terrain.length === 0 || animal.terrain.includes(tile.terrain);
  return tile.location === null && terrainMatches && matchingNeighbors >= 2;
}

/** "You can buy mounts in a city that is on the appropriate terrain (and also has at least two of
 * the same land adjacent to it)" -- culture-agnostic, unlike Hirelings: only the city's own terrain
 * has to match, not which culture built it. */
export function qualifiesForBuyingMount(tile: HexTile, matchingNeighbors: number, mount: AnimalDef): boolean {
  const terrainMatches = mount.terrain.includes(tile.terrain);
  return tile.location !== null && CITY_OR_FORTRESS.has(tile.location) && terrainMatches && matchingNeighbors >= 2;
}

/** Immutably ties a `PendingDungeon` to the hex at `coord` -- called from App.tsx the moment a
 * hex's dungeon is rolled for the very first time (see CLAUDE.md's per-hex dungeon persistence
 * note). A no-op if the hex isn't known yet, which shouldn't happen in practice -- this only ever
 * runs while standing on one. */
export function withDungeonRunId(world: WorldState, coord: HexCoord, runId: string): WorldState {
  const key = hexKey(coord);
  const tile = world.tiles[key];
  if (!tile) return world;
  return { ...world, tiles: { ...world.tiles, [key]: { ...tile, dungeonRunId: runId } } };
}

/** "Ask" City Action (`docs/game-rules-reference.md` lines 978-985) -- rolls a hex side and steps
 * clockwise through `from`'s own six neighbors for the first one that's land with no location: "In
 * this hex there will be a dungeon ... If the hex has Water or another City or Ruins, go clockwise
 * to the next hex until you find land that has no location and isn't water." Every neighbor of an
 * already-entered hex is guaranteed to already be revealed (see `revealNeighborsInPlace`), so this
 * only ever reads `tiles` -- it never needs to reveal anything itself. Returns `null` in the
 * should-be-impossible case that all six neighbors are Water/City/Fortress/Ruins/Rocks, since the
 * rulebook doesn't cover that.
 */
export function findAskedDungeonHex(world: WorldState, from: HexCoord, rng: RNG): HexCoord | null {
  const roll = rollDie(rng);
  for (let i = 0; i < 6; i++) {
    const dir = HEX_DIRECTIONS[(roll - 1 + i) % 6]!;
    const coord = { q: from.q + dir.q, r: from.r + dir.r };
    const tile = world.tiles[hexKey(coord)];
    if (tile && tile.terrain !== "water" && tile.location === null) return coord;
  }
  return null;
}

/** Companion to `withDungeonRunId` -- immutably flags a hex as "a dungeon has been found nearby"
 * (see `HexTile.dungeonMarked`) without minting a run for it yet. */
export function withDungeonMarked(world: WorldState, coord: HexCoord): WorldState {
  const key = hexKey(coord);
  const tile = world.tiles[key];
  if (!tile) return world;
  return { ...world, tiles: { ...world.tiles, [key]: { ...tile, dungeonMarked: true } } };
}

/** True once the hex at `coord` has been permanently barred by a failed Thug Life escape (see
 * `HexTile`'s -- no, `WorldState.bannedHexes`' -- own doc comment). The one place this list should
 * ever be read, so the `?? []` back-compat default for a pre-#58 persisted session lives here once
 * instead of at every call site. */
export function isBannedHex(world: WorldState, coord: HexCoord): boolean {
  return (world.bannedHexes ?? []).includes(hexKey(coord));
}

/** Immutably bars a hex for good -- "Thug Life" (`town.ts`'s `resolveThugLife()`) is the only
 * caller today. Idempotent (a second call is a no-op) even though nothing currently re-bans an
 * already-banned hex. */
export function withBannedHex(world: WorldState, coord: HexCoord): WorldState {
  if (isBannedHex(world, coord)) return world;
  return { ...world, bannedHexes: [...(world.bannedHexes ?? []), hexKey(coord)] };
}

/** The player starts on a human city on a plain (fixed, not rolled -- "Choose a hex to start with
 * ... it will be a human city on a plain"), with its 6 neighbors already revealed so there's
 * somewhere to go without a wasted first move. Its name ("Haven") is likewise fixed rather than
 * rolled via `rollCityName()`, same "fixed, not rolled" precedent as its terrain/location -- rolling
 * it would also shift every existing `rng` fixture's die sequence by two for no rules-driven reason
 * (the rulebook doesn't roll a name for the starting hex either). */
export function createInitialWorldState(rng: RNG = Math.random): WorldState {
  const home: HexCoord = { q: 0, r: 0 };
  const climate: Climate = "hot";
  const tiles: Record<string, HexTile> = {
    [hexKey(home)]: { terrain: "plain", location: "humanCity", name: "Haven" },
  };
  revealNeighborsInPlace(tiles, home, climate, rng);
  return { climate, home, player: home, tiles, hasBoat: false, bannedHexes: [] };
}
