import { rollDie } from "./dice.ts";
import type { RNG } from "./rng.ts";
import {
  COLD_TERRAIN_TABLE,
  HOT_TERRAIN_TABLE,
  LOCATION_TABLE,
  type Climate,
  type ColdTerrain,
  type HotTerrain,
  type Land,
  type LocationKind,
  type Terrain,
} from "../data/hexTables.ts";

export interface HexCoord {
  q: number;
  r: number;
}

export function hexKey(c: HexCoord): string {
  return `${c.q},${c.r}`;
}

/** Axial neighbor offsets, pointy-top hexes. */
export const HEX_DIRECTIONS: readonly HexCoord[] = [
  { q: 1, r: 0 },
  { q: 1, r: -1 },
  { q: 0, r: -1 },
  { q: -1, r: 0 },
  { q: -1, r: 1 },
  { q: 0, r: 1 },
];

export function hexNeighbors(c: HexCoord): HexCoord[] {
  return HEX_DIRECTIONS.map((d) => ({ q: c.q + d.q, r: c.r + d.r }));
}

export interface HexTile {
  terrain: Terrain;
  location: LocationKind | null;
  /** The PendingDungeon.id found here, once "Enter Dungeon" has been used on this hex -- lets a
   * later visit (same character returning, or a new one taking over) resume the same dungeon
   * instead of rolling fresh. Set once, on first entry; never cleared, even once beaten. */
  dungeonRunId?: string;
}

export interface WorldState {
  /** Always "hot" for now -- the cold table is real data but nothing picks it yet. */
  climate: Climate;
  home: HexCoord;
  player: HexCoord;
  /** Sparse, populated lazily -- a tile only exists once its terrain+location are rolled,
   * mirroring DungeonState's segments (which likewise don't exist until a door reveals them). The
   * rulebook rolls a hex's location the same moment it rolls its terrain (both happen when its
   * *parent* hex is entered), so there's no separate "terrain known, location TBD" state to model
   * -- presence in this map means fully known. */
  tiles: Record<string, HexTile>;
}

/** `current` is trusted to belong to `climate`'s own terrain set (a hot-climate world only ever
 * produces HotTerrain values, a cold one only ColdTerrain) -- true by construction, since every
 * tile in a WorldState is generated by this same function against the same fixed climate. */
function nextTerrain(current: Terrain, climate: Climate, roll: number): Terrain {
  if (climate === "hot") return HOT_TERRAIN_TABLE[roll]![current as HotTerrain];
  return COLD_TERRAIN_TABLE[roll]![current as ColdTerrain];
}

/**
 * "When entering a hex, first determine the neighboring hexes. Roll one die in the Terrain table
 * for each hex. After that, roll one more die for each hex to see if there is a location. If it
 * lands on 6, there is a location -- roll on the Location table." Mutates `tiles` in place (works
 * whether it's a plain object, as in `createInitialWorldState`, or an Immer `Draft`, as in
 * `hexReducer`'s `produce()`) and never overwrites an already-revealed tile, so a hex shared by
 * two revealed neighbors only ever gets rolled once.
 */
export function revealNeighborsInPlace(
  tiles: Record<string, HexTile>,
  of: HexCoord,
  climate: Climate,
  rng: RNG,
): void {
  const parent = tiles[hexKey(of)];
  if (!parent) return;
  for (const neighbor of hexNeighbors(of)) {
    const key = hexKey(neighbor);
    if (tiles[key]) continue;
    const terrain = nextTerrain(parent.terrain, climate, rollDie(rng));
    const hasLocation = rollDie(rng) === 6;
    const location = hasLocation ? LOCATION_TABLE[rollDie(rng)]![terrain as Land] : null;
    tiles[key] = { terrain, location };
  }
}

/** Immutably ties a `PendingDungeon` to the hex at `coord` -- App.tsx's two call sites are a hex's
 * first-ever "Enter Dungeon" and "Start a New Dungeon" re-tying the hex to whatever gets rolled
 * next (see CLAUDE.md's per-hex dungeon persistence note). A no-op if the hex isn't known yet,
 * which shouldn't happen in practice -- both call sites only ever run while standing on one. */
export function withDungeonRunId(world: WorldState, coord: HexCoord, runId: string): WorldState {
  const key = hexKey(coord);
  const tile = world.tiles[key];
  if (!tile) return world;
  return { ...world, tiles: { ...world.tiles, [key]: { ...tile, dungeonRunId: runId } } };
}

/** The player starts on a human city on a plain (fixed, not rolled -- "Choose a hex to start with
 * ... it will be a human city on a plain"), with its 6 neighbors already revealed so there's
 * somewhere to go without a wasted first move. */
export function createInitialWorldState(rng: RNG = Math.random): WorldState {
  const home: HexCoord = { q: 0, r: 0 };
  const climate: Climate = "hot";
  const tiles: Record<string, HexTile> = {
    [hexKey(home)]: { terrain: "plain", location: "humanCity" },
  };
  revealNeighborsInPlace(tiles, home, climate, rng);
  return { climate, home, player: home, tiles };
}
